DELIMITER //

DROP PROCEDURE IF EXISTS sp_seed_master_subcategories //
CREATE PROCEDURE sp_seed_master_subcategories()
BEGIN

	INSERT INTO Subcategory (name, id_category_fk)
	SELECT src.canonical_subcategory, c.id_category
	FROM (
		SELECT
			MIN(raw_pairs.raw_subcategory) AS canonical_subcategory,
			LOWER(TRIM(raw_pairs.raw_category)) AS normalized_category,
			LOWER(TRIM(raw_pairs.raw_subcategory)) AS normalized_subcategory
		FROM (
			SELECT 'Accesorios Herramientas Eléctricas' AS raw_category, 'Accesorios Esmeriles' AS raw_subcategory
			UNION ALL SELECT 'Accesorios Herramientas Eléctricas', 'Accesorios para Atornilladores'
			UNION ALL SELECT 'Accesorios Herramientas Eléctricas', 'Accesorios para Lijadoras'
			UNION ALL SELECT 'Accesorios Herramientas Eléctricas', 'Accesorios para Mototools'
			UNION ALL SELECT 'Accesorios Herramientas Eléctricas', 'Accesorios para Multiherramientas'
			UNION ALL SELECT 'Accesorios Herramientas Eléctricas', 'Accesorios para Pulidoras'
			UNION ALL SELECT 'Accesorios Herramientas Eléctricas', 'Accesorios para Sierras Caladoras'
			UNION ALL SELECT 'Accesorios Herramientas Eléctricas', 'Accesorios para Sierras y Tronzadoras'
			UNION ALL SELECT 'Accesorios Herramientas Eléctricas', 'Accesorios para Taladros y Rotomartillos'
			UNION ALL SELECT 'Accesorios Herramientas Eléctricas', 'Brocas Especiales'
			UNION ALL SELECT 'Accesorios Herramientas Eléctricas', 'Brocas Para Cerámica'
			UNION ALL SELECT 'Accesorios Herramientas Eléctricas', 'Brocas Para Concreto'
			UNION ALL SELECT 'Accesorios Herramientas Eléctricas', 'Brocas Para Madera'
			UNION ALL SELECT 'Accesorios Herramientas Eléctricas', 'Brocas Para Metal'
			UNION ALL SELECT 'Accesorios Herramientas Eléctricas', 'Disco Corte Esmeriles'
			UNION ALL SELECT 'Accesorios Herramientas Eléctricas', 'Disco Desbaste Esmeriles'
			UNION ALL SELECT 'Accesorios Herramientas Eléctricas', 'Pistolas De Calor'
			UNION ALL SELECT 'Accesorios para Herramientas', 'Accesorios de organización de herramientas'
			UNION ALL SELECT 'Accesorios para Herramientas', 'Accesorios manuales'
			UNION ALL SELECT 'Accesorios para herramientas eléctricas', 'Accesorios para esmeriles'
			UNION ALL SELECT 'Accesorios para herramientas eléctricas', 'Accesorios para sierras'
			UNION ALL SELECT 'Accesorios para herramientas eléctricas', 'Accesorios para taladros'
			UNION ALL SELECT 'Adhesivos y Selladores', 'Adhesivos de construcción'
			UNION ALL SELECT 'Adhesivos y Selladores', 'Adhesivos de montaje y construcción'
			UNION ALL SELECT 'Adhesivos y Selladores', 'Adhesivos especiales'
			UNION ALL SELECT 'Adhesivos y Selladores', 'Adhesivos para madera'
			UNION ALL SELECT 'Adhesivos y Selladores', 'Adhesivos para PVC y tuberías'
			UNION ALL SELECT 'Adhesivos y Selladores', 'Cintas selladoras y para roscas'
			UNION ALL SELECT 'Adhesivos y Selladores', 'Espumas de poliuretano'
			UNION ALL SELECT 'Adhesivos y Selladores', 'Espumas y anclajes químicos'
			UNION ALL SELECT 'Adhesivos y Selladores', 'Masillas y selladores especiales'
			UNION ALL SELECT 'Adhesivos y Selladores', 'Removedores y limpiadores de adhesivos'
			UNION ALL SELECT 'Adhesivos y Selladores', 'Selladores'
			UNION ALL SELECT 'Adhesivos y Selladores', 'Selladores acrílicos'
			UNION ALL SELECT 'Adhesivos y Selladores', 'Selladores de poliuretano'
			UNION ALL SELECT 'Adhesivos y Selladores', 'Siliconas y selladores de silicona'
			UNION ALL SELECT 'Almacenamiento y Estanterías', 'Almacenamiento metálico'
			UNION ALL SELECT 'Almacenamiento y Estanterías', 'Almacenamiento plástico'
			UNION ALL SELECT 'Almacenamiento y Estanterías', 'Cajas y contenedores'
			UNION ALL SELECT 'Almacenamiento y Estanterías', 'Estanterías pesadas'
			UNION ALL SELECT 'Almacenamiento y Estanterías', 'Organizadores'
			UNION ALL SELECT 'Automotriz', 'Accesorios para vehículo'
			UNION ALL SELECT 'Automotriz', 'Limpieza y cuidado automotriz'
			UNION ALL SELECT 'Baños y Sanitarios', 'Accesorios de baño'
			UNION ALL SELECT 'Baños y Sanitarios', 'Accesorios de seguridad para baño'
			UNION ALL SELECT 'Baños y Sanitarios', 'Accesorios para ducha'
			UNION ALL SELECT 'Baños y Sanitarios', 'Aparatos sanitarios'
			UNION ALL SELECT 'Baños y Sanitarios', 'Bañeras y tinas'
			UNION ALL SELECT 'Baños y Sanitarios', 'Cabinas y mamparas de baño'
			UNION ALL SELECT 'Baños y Sanitarios', 'Complementos varios para baño'
			UNION ALL SELECT 'Baños y Sanitarios', 'Espejos y botiquines'
			UNION ALL SELECT 'Baños y Sanitarios', 'Grifería para ducha y tina'
			UNION ALL SELECT 'Baños y Sanitarios', 'Grifería para lavamanos'
			UNION ALL SELECT 'Baños y Sanitarios', 'Griferías para baño'
			UNION ALL SELECT 'Baños y Sanitarios', 'Lavamanos y lavabos'
			UNION ALL SELECT 'Baños y Sanitarios', 'Muebles de baño'
			UNION ALL SELECT 'Baños y Sanitarios', 'Platos de ducha y bases'
			UNION ALL SELECT 'Baños y Sanitarios', 'Sistemas de descarga y cisternas'
			UNION ALL SELECT 'Bombas y Sistemas Hidráulicos', 'Accesorios hidráulicos'
			UNION ALL SELECT 'Bombas y Sistemas Hidráulicos', 'Accesorios para bombas'
			UNION ALL SELECT 'Bombas y Sistemas Hidráulicos', 'Bombas de agua'
			UNION ALL SELECT 'Bombas y Sistemas Hidráulicos', 'Bombas especiales'
			UNION ALL SELECT 'Bombas y Sistemas Hidráulicos', 'Sistemas de presión'
			UNION ALL SELECT 'Cocina', 'Accesorios murales para cocina'
			UNION ALL SELECT 'Cocina', 'Accesorios para fregadero de cocina'
			UNION ALL SELECT 'Cocina', 'Accesorios varios de cocina'
			UNION ALL SELECT 'Cocina', 'Basureros y sistemas de reciclaje para cocina'
			UNION ALL SELECT 'Cocina', 'Campanas y extracción de cocina'
			UNION ALL SELECT 'Cocina', 'Fregaderos y accesorios'
			UNION ALL SELECT 'Cocina', 'Fregaderos y lavaplatos'
			UNION ALL SELECT 'Cocina', 'Grifería de cocina'
			UNION ALL SELECT 'Cocina', 'Griferías de cocina'
			UNION ALL SELECT 'Cocina', 'Muebles de cocina'
			UNION ALL SELECT 'Cocina', 'Organización interior de muebles de cocina'
			UNION ALL SELECT 'Cocina', 'Plomería para cocina'
			UNION ALL SELECT 'Construcción y Albañilería', 'Accesorios de encofrado y hormigón'
			UNION ALL SELECT 'Construcción y Albañilería', 'Accesorios de seguridad y señalización de obra'
			UNION ALL SELECT 'Construcción y Albañilería', 'Alicatado manual y cerámica'
			UNION ALL SELECT 'Construcción y Albañilería', 'Andamios y accesos temporales'
			UNION ALL SELECT 'Construcción y Albañilería', 'Aplicación e impermeabilización en obra'
			UNION ALL SELECT 'Construcción y Albañilería', 'Apuntalamiento y soportes provisionales'
			UNION ALL SELECT 'Construcción y Albañilería', 'Colado de concreto y mortero'
			UNION ALL SELECT 'Construcción y Albañilería', 'Compactación y relleno manual'
			UNION ALL SELECT 'Construcción y Albañilería', 'Drywall y construcción en seco'
			UNION ALL SELECT 'Construcción y Albañilería', 'Encofrado y cimbras'
			UNION ALL SELECT 'Construcción y Albañilería', 'Equipos De Albañilería'
			UNION ALL SELECT 'Construcción y Albañilería', 'Equipos de obra'
			UNION ALL SELECT 'Construcción y Albañilería', 'Herramientas para albañil'
			UNION ALL SELECT 'Construcción y Albañilería', 'Mampostería y bloque'
			UNION ALL SELECT 'Construcción y Albañilería', 'Pavimentos y adoquines'
			UNION ALL SELECT 'Construcción y Albañilería', 'Preparación de terreno y demolición pesada'
			UNION ALL SELECT 'Construcción y Albañilería', 'Revestimientos y frisos'
			UNION ALL SELECT 'Construcción y Albañilería', 'Transporte y manipulación de materiales'
			UNION ALL SELECT 'Electricidad', 'Accesorios'
			UNION ALL SELECT 'Electricidad', 'Automatización'
			UNION ALL SELECT 'Electricidad', 'Cables eléctricos'
			UNION ALL SELECT 'Electricidad', 'Cables Y Conductores'
			UNION ALL SELECT 'Electricidad', 'Cajas y accesorios'
			UNION ALL SELECT 'Electricidad', 'Canalización y bandejas'
			UNION ALL SELECT 'Electricidad', 'Canalizaciones'
			UNION ALL SELECT 'Electricidad', 'Conectores'
			UNION ALL SELECT 'Electricidad', 'enchufes o clavijas'
			UNION ALL SELECT 'Electricidad', 'Interruptores'
			UNION ALL SELECT 'Electricidad', 'Protecciones'
			UNION ALL SELECT 'Electricidad', 'Protecciones eléctricas'
			UNION ALL SELECT 'Electricidad', 'Tomacorrientes'
			UNION ALL SELECT 'Equipos De Taller Y Automotriz', 'Almacenamiento Y Organización'
			UNION ALL SELECT 'Equipos De Taller Y Automotriz', 'Bancadas Y Mesas'
			UNION ALL SELECT 'Equipos de taller y automotriz', 'Compresores y neumática'
			UNION ALL SELECT 'Equipos de taller y automotriz', 'Elevación y soporte'
			UNION ALL SELECT 'Equipos De Taller Y Automotriz', 'Equipos De Aire Acondicionado'
			UNION ALL SELECT 'Equipos De Taller Y Automotriz', 'Equipos De Diagnóstico'
			UNION ALL SELECT 'Equipos De Taller Y Automotriz', 'Equipos De Elevación Y Manipulación'
			UNION ALL SELECT 'Equipos De Taller Y Automotriz', 'Equipos De Ruedas Y Llantas'
			UNION ALL SELECT 'Equipos de taller y automotriz', 'Equipos de servicio'
			UNION ALL SELECT 'Equipos De Taller Y Automotriz', 'Equipos De Suspensión Y Dirección'
			UNION ALL SELECT 'Equipos De Taller Y Automotriz', 'Equipos De Transmisión Y Freno'
			UNION ALL SELECT 'Equipos De Taller Y Automotriz', 'Equipos Especiales De Motor'
			UNION ALL SELECT 'Equipos De Taller Y Automotriz', 'Herramientas Varias Taller'
			UNION ALL SELECT 'Equipos De Taller Y Automotriz', 'Limpieza Y Mantenimiento'
			UNION ALL SELECT 'Equipos De Taller Y Automotriz', 'Seguridad Y Protección'
			UNION ALL SELECT 'Equipos De Taller Y Automotriz', 'Sistemas De Aire Y Lubricación'
			UNION ALL SELECT 'Ferretería General', 'Accesorios para cables'
			UNION ALL SELECT 'Ferretería General', 'Accesorios varios de ferretería'
			UNION ALL SELECT 'Ferretería General', 'Cadenas y cables'
			UNION ALL SELECT 'Ferretería General', 'Cierres y pestillos'
			UNION ALL SELECT 'Ferretería General', 'Escuadras y pletinas'
			UNION ALL SELECT 'Ferretería General', 'Ganchos y anillas'
			UNION ALL SELECT 'Ferretería General', 'Grapas y abrazaderas'
			UNION ALL SELECT 'Ferretería General', 'Ruedas y rodajas'
			UNION ALL SELECT 'Ferretería General', 'Soportes y accesorios de fijación'
			UNION ALL SELECT 'Ferretería General', 'Topes y niveladores'
			UNION ALL SELECT 'Gas', 'Accesorios De Instalación'
			UNION ALL SELECT 'Gas', 'Accesorios Generales'
			UNION ALL SELECT 'Gas', 'Accesorios para instalación de gas'
			UNION ALL SELECT 'Gas', 'Accesorios Para Tubería'
			UNION ALL SELECT 'Gas', 'Conexiones De Acero Negro'
			UNION ALL SELECT 'Gas', 'Conexiones De Cobre'
			UNION ALL SELECT 'Gas', 'Conexiones Galvanizadas'
			UNION ALL SELECT 'Gas', 'Conexiones PEAD'
			UNION ALL SELECT 'Gas', 'Herramientas Para Instalación'
			UNION ALL SELECT 'Gas', 'Instalaciones Domésticas'
			UNION ALL SELECT 'Gas', 'Instalaciones Industriales'
			UNION ALL SELECT 'Gas', 'Mangueras'
			UNION ALL SELECT 'Gas', 'Medición Y Control'
			UNION ALL SELECT 'Gas', 'Reguladores'
			UNION ALL SELECT 'Gas', 'Seguridad'
			UNION ALL SELECT 'Gas', 'Tuberías'
			UNION ALL SELECT 'Gas', 'Válvulas'
			UNION ALL SELECT 'Gas', 'Válvulas y llaves para gas'
			UNION ALL SELECT 'Generadores Eléctricos y Herramientas a Motor', 'Equipos a motor'
			UNION ALL SELECT 'Generadores Eléctricos y Herramientas a Motor', 'Generadores eléctricos'
			UNION ALL SELECT 'Generadores Eléctricos y Herramientas a Motor', 'Motobombas'
			UNION ALL SELECT 'Herrajes y Accesorios', 'Anillas, argollas y ganchos'
			UNION ALL SELECT 'Herrajes y Accesorios', 'Bisagras'
			UNION ALL SELECT 'Herrajes y Accesorios', 'Candados'
			UNION ALL SELECT 'Herrajes y Accesorios', 'Cerraduras y cilindros'
			UNION ALL SELECT 'Herrajes y Accesorios', 'Herrajes para muebles'
			UNION ALL SELECT 'Herrajes y Accesorios', 'Herrajes para portones'
			UNION ALL SELECT 'Herrajes y Accesorios', 'Herrajes para puertas'
			UNION ALL SELECT 'Herrajes y Accesorios', 'Herrajes para puertas corredizas'
			UNION ALL SELECT 'Herrajes y Accesorios', 'Herrajes para ventanas'
			UNION ALL SELECT 'Herrajes y Accesorios', 'Herrajes Y Accesorios Para Muebles'
			UNION ALL SELECT 'Herrajes y Accesorios', 'Manijas y pomos'
			UNION ALL SELECT 'Herrajes y Accesorios', 'Pasadores y cerrojos'
			UNION ALL SELECT 'Herrajes y Accesorios', 'Picaportes y pestillos'
			UNION ALL SELECT 'Herrajes y Accesorios', 'Placas y embellecedores'
			UNION ALL SELECT 'Herrajes y Accesorios', 'Soportes y escuadras'
			UNION ALL SELECT 'Herrajes y Accesorios', 'Tensores y accesorios de cable'
			UNION ALL SELECT 'Herrajes y Accesorios', 'Topes y burletes'
			UNION ALL SELECT 'Herramientas de Medición y Diagnóstico', 'Diagnóstico electrónico portátil'
			UNION ALL SELECT 'Herramientas de Medición y Diagnóstico', 'Inspección visual y diagnóstico'
			UNION ALL SELECT 'Herramientas de Medición y Diagnóstico', 'Instrumentos de medición eléctrica'
			UNION ALL SELECT 'Herramientas de Medición y Diagnóstico', 'Instrumentos de medición láser'
			UNION ALL SELECT 'Herramientas de Medición y Diagnóstico', 'Instrumentos de medición mecánica'
			UNION ALL SELECT 'Herramientas de Medición y Diagnóstico', 'Medición HVAC y climatización'
			UNION ALL SELECT 'Herramientas de Medición y Diagnóstico', 'Medición industrial y procesos'
			UNION ALL SELECT 'Herramientas de Medición y Diagnóstico', 'Medición para plomería y gas'
			UNION ALL SELECT 'Herramientas de Medición y Diagnóstico', 'Medición y diagnóstico automotriz'
			UNION ALL SELECT 'Herramientas de Medición y Diagnóstico', 'Medición y diagnóstico eléctrico'
			UNION ALL SELECT 'Herramientas de Medición y Diagnóstico', 'Metrología de precisión'
			UNION ALL SELECT 'Herramientas de Medición y Diagnóstico', 'Topografía y nivelación'
			UNION ALL SELECT 'Herramientas Eléctricas', 'Agua'
			UNION ALL SELECT 'Herramientas Eléctricas', 'Atornillado eléctrico/Atornilladores con cable'
			UNION ALL SELECT 'Herramientas Eléctricas', 'Atornillado eléctrico/Atornilladores de impacto con cable'
			UNION ALL SELECT 'Herramientas Eléctricas', 'Atornillado eléctrico/Atornilladores para yeso'
			UNION ALL SELECT 'Herramientas Eléctricas', 'Carpintería eléctrica/Cepillos eléctricos'
			UNION ALL SELECT 'Herramientas Eléctricas', 'Carpintería eléctrica/Engalletadoras and uniones'
			UNION ALL SELECT 'Herramientas Eléctricas', 'Carpintería eléctrica/Engalletadoras y uniones'
			UNION ALL SELECT 'Herramientas Eléctricas', 'Carpintería eléctrica/Fresadoras y routers'
			UNION ALL SELECT 'Herramientas Eléctricas', 'Carpintería eléctrica/Lijadoras combinadas de banco'
			UNION ALL SELECT 'Herramientas Eléctricas', 'Carpintería eléctrica/Sierras especiales de carpintero'
			UNION ALL SELECT 'Herramientas Eléctricas', 'Corte y desbaste eléctricos/Amoladoras angulares'
			UNION ALL SELECT 'Herramientas Eléctricas', 'Corte y desbaste eléctricos/Amoladoras rectas'
			UNION ALL SELECT 'Herramientas Eléctricas', 'Corte y desbaste eléctricos/Esmeriles de banco'
			UNION ALL SELECT 'Herramientas Eléctricas', 'Corte y desbaste eléctricos/Pulidoras angulares'
			UNION ALL SELECT 'Herramientas Eléctricas', 'Esmeriles y amoladoras eléctricas'
			UNION ALL SELECT 'Herramientas Eléctricas', 'Fijación eléctrica/Clavadoras eléctricas'
			UNION ALL SELECT 'Herramientas Eléctricas', 'Fijación eléctrica/Remachadoras eléctricas'
			UNION ALL SELECT 'Herramientas Eléctricas', 'Herramientas de calor eléctricas/Decapadores eléctricos'
			UNION ALL SELECT 'Herramientas Eléctricas', 'Herramientas de calor eléctricas/Pistolas de aire caliente'
			UNION ALL SELECT 'Herramientas Eléctricas', 'Herramientas de calor eléctricas/Soldadores de aire caliente'
			UNION ALL SELECT 'Herramientas Eléctricas', 'Herramientas eléctricas especiales/Corte especializado'
			UNION ALL SELECT 'Herramientas Eléctricas', 'Herramientas eléctricas especiales/Herramientas rotativas'
			UNION ALL SELECT 'Herramientas Eléctricas', 'Herramientas eléctricas especiales/Otras herramientas especiales'
			UNION ALL SELECT 'Herramientas Eléctricas', 'Juegos de herramientas eléctricas/Juegos combinados'
			UNION ALL SELECT 'Herramientas Eléctricas', 'Juegos de herramientas eléctricas/Juegos para construcción'
			UNION ALL SELECT 'Herramientas Eléctricas', 'Lijado y pulido eléctricos/Lijadoras de banda'
			UNION ALL SELECT 'Herramientas Eléctricas', 'Lijado y pulido eléctricos/Lijadoras de detalle y delta'
			UNION ALL SELECT 'Herramientas Eléctricas', 'Lijado y pulido eléctricos/Lijadoras de pared para yeso'
			UNION ALL SELECT 'Herramientas Eléctricas', 'Lijado y pulido eléctricos/Lijadoras orbitales'
			UNION ALL SELECT 'Herramientas Eléctricas', 'Lijado y pulido eléctricos/Pulidoras de carrocería'
			UNION ALL SELECT 'Herramientas Eléctricas', 'Sierras eléctricas'
			UNION ALL SELECT 'Herramientas Eléctricas', 'Sierras eléctricas portátiles/Sierras caladoras'
			UNION ALL SELECT 'Herramientas Eléctricas', 'Sierras eléctricas portátiles/Sierras circulares'
			UNION ALL SELECT 'Herramientas Eléctricas', 'Sierras eléctricas portátiles/Sierras de banda portátiles'
			UNION ALL SELECT 'Herramientas Eléctricas', 'Sierras eléctricas portátiles/Sierras para azulejos portátiles'
			UNION ALL SELECT 'Herramientas Eléctricas', 'Sierras eléctricas portátiles/Sierras sable (reciprocantes)'
			UNION ALL SELECT 'Herramientas Eléctricas', 'Sierras estacionarias/Cortadoras de cerámica de mesa'
			UNION ALL SELECT 'Herramientas Eléctricas', 'Sierras estacionarias/Sierras de cinta de taller'
			UNION ALL SELECT 'Herramientas Eléctricas', 'Sierras estacionarias/Sierras de mesa para madera'
			UNION ALL SELECT 'Herramientas Eléctricas', 'Sierras estacionarias/Sierras ingleteadoras'
			UNION ALL SELECT 'Herramientas Eléctricas', 'Sierras estacionarias/Tronzadoras de metal de banco'
			UNION ALL SELECT 'Herramientas Eléctricas', 'Taladros eléctricos'
			UNION ALL SELECT 'Herramientas Eléctricas', 'Taladros y perforación eléctrica/Herramientas de mezcla'
			UNION ALL SELECT 'Herramientas Eléctricas', 'Taladros y perforación eléctrica/Martillos perforadores y demoledores'
			UNION ALL SELECT 'Herramientas Eléctricas', 'Taladros y perforación eléctrica/Taladros con cable'
			UNION ALL SELECT 'Herramientas Eléctricas', 'Taladros y perforación eléctrica/Taladros de banco y columna'
			UNION ALL SELECT 'Herramientas Especializadas y Técnicas', 'Herramientas automotrices – especiales'
			UNION ALL SELECT 'Herramientas Especializadas y Técnicas', 'Herramientas automotrices – frenos'
			UNION ALL SELECT 'Herramientas Especializadas y Técnicas', 'Herramientas automotrices – motor e inyección'
			UNION ALL SELECT 'Herramientas Especializadas y Técnicas', 'Herramientas automotrices – suspensión y dirección'
			UNION ALL SELECT 'Herramientas Especializadas y Técnicas', 'Herramientas cerrajería – instalación'
			UNION ALL SELECT 'Herramientas Especializadas y Técnicas', 'Herramientas drywall y construcción ligera'
			UNION ALL SELECT 'Herramientas Especializadas y Técnicas', 'Herramientas electrónica y precisión'
			UNION ALL SELECT 'Herramientas Especializadas y Técnicas', 'Herramientas estructuras ligeras y carpintería metálica técnica'
			UNION ALL SELECT 'Herramientas Especializadas y Técnicas', 'Herramientas fibra óptica'
			UNION ALL SELECT 'Herramientas Especializadas y Técnicas', 'Herramientas hidráulicas manuales'
			UNION ALL SELECT 'Herramientas Especializadas y Técnicas', 'Herramientas HVAC y refrigeración'
			UNION ALL SELECT 'Herramientas Especializadas y Técnicas', 'Herramientas mantenimiento industrial'
			UNION ALL SELECT 'Herramientas Especializadas y Técnicas', 'Herramientas montaje de paneles solares'
			UNION ALL SELECT 'Herramientas Especializadas y Técnicas', 'Herramientas montaje eléctrico industrial'
			UNION ALL SELECT 'Herramientas Especializadas y Técnicas', 'Herramientas montaje sistemas modulares'
			UNION ALL SELECT 'Herramientas Especializadas y Técnicas', 'Herramientas para carpintero'
			UNION ALL SELECT 'Herramientas Especializadas y Técnicas', 'Herramientas para electricista'
			UNION ALL SELECT 'Herramientas Especializadas y Técnicas', 'Herramientas para mecánico'
			UNION ALL SELECT 'Herramientas Especializadas y Técnicas', 'Herramientas para pisos y revestimientos técnicos'
			UNION ALL SELECT 'Herramientas Especializadas y Técnicas', 'Herramientas redes y telecom'
			UNION ALL SELECT 'Herramientas Especializadas y Técnicas', 'Herramientas techos metálicos y panelería'
			UNION ALL SELECT 'Herramientas Especializadas y Técnicas', 'Herramientas técnicas de plomería y gas'
			UNION ALL SELECT 'Herramientas Especializadas y Técnicas', 'Herramientas vidrio y aluminio'
			UNION ALL SELECT 'Herramientas Inalámbricas', 'Atornillado inalámbrico/Atornilladores de impacto'
			UNION ALL SELECT 'Herramientas Inalámbricas', 'Atornillado inalámbrico/Atornilladores tradicionales'
			UNION ALL SELECT 'Herramientas Inalámbricas', 'Automotriz inalámbrico/Herramientas automotrices'
			UNION ALL SELECT 'Herramientas Inalámbricas', 'Baterías y cargadores/Baterías'
			UNION ALL SELECT 'Herramientas Inalámbricas', 'Baterías y cargadores/Cargadores'
			UNION ALL SELECT 'Herramientas Inalámbricas', 'Baterías y cargadores/Estaciones de carga'
			UNION ALL SELECT 'Herramientas Inalámbricas', 'Bombas inalámbricas/Bombas de agua'
			UNION ALL SELECT 'Herramientas Inalámbricas', 'Bombas inalámbricas/Bombas de aire'
			UNION ALL SELECT 'Herramientas Inalámbricas', 'Corte y desbaste inalámbrico/Amoladoras angulares'
			UNION ALL SELECT 'Herramientas Inalámbricas', 'Fijación inalámbrica/Grapadoras inalámbricas'
			UNION ALL SELECT 'Herramientas Inalámbricas', 'Fijación inalámbrica/Remachadoras inalámbricas'
			UNION ALL SELECT 'Herramientas Inalámbricas', 'Herramientas especializadas inalámbricas/Multiherramientas'
			UNION ALL SELECT 'Herramientas Inalámbricas', 'Herramientas especializadas inalámbricas/Otros'
			UNION ALL SELECT 'Herramientas Inalámbricas', 'Herramientas inalámbricas varias'
			UNION ALL SELECT 'Herramientas Inalámbricas', 'Herramientas rotativas inalámbricas/Herramientas rotativas'
			UNION ALL SELECT 'Herramientas Inalámbricas', 'HVAC inalámbrico/Herramientas HVAC'
			UNION ALL SELECT 'Herramientas Inalámbricas', 'Juegos inalámbricos/Juegos combinados'
			UNION ALL SELECT 'Herramientas Inalámbricas', 'Lijado inalámbrico/Lijadoras de banda'
			UNION ALL SELECT 'Herramientas Inalámbricas', 'Sierras inalámbricas'
			UNION ALL SELECT 'Herramientas Inalámbricas', 'Sierras inalámbricas/Sierras caladoras'
			UNION ALL SELECT 'Herramientas Inalámbricas', 'Sierras inalámbricas/Sierras circulares'
			UNION ALL SELECT 'Herramientas Inalámbricas', 'Sierras inalámbricas/Sierras especializadas'
			UNION ALL SELECT 'Herramientas Inalámbricas', 'Taladros inalámbricos/Taladros inalámbricos convencionales'
			UNION ALL SELECT 'Herramientas Manuales', 'Albañilería/Alicatado'
			UNION ALL SELECT 'Herramientas Manuales', 'Albañilería/Herramientas varias'
			UNION ALL SELECT 'Herramientas Manuales', 'Albañilería/Llanas o Palustras'
			UNION ALL SELECT 'Herramientas Manuales', 'Albañilería/Martillos y cinceles'
			UNION ALL SELECT 'Herramientas Manuales', 'Albañilería/Paletas de albañil'
			UNION ALL SELECT 'Herramientas Manuales', 'Alicates'
			UNION ALL SELECT 'Herramientas Manuales', 'Alicates y pinzas/Alicates de corte'
			UNION ALL SELECT 'Herramientas Manuales', 'Alicates y pinzas/Alicates de presión'
			UNION ALL SELECT 'Herramientas Manuales', 'Alicates y pinzas/Alicates de punta'
			UNION ALL SELECT 'Herramientas Manuales', 'Alicates y pinzas/Alicates especiales'
			UNION ALL SELECT 'Herramientas Manuales', 'Alicates y pinzas/Alicates para anillos'
			UNION ALL SELECT 'Herramientas Manuales', 'Alicates y pinzas/Alicates universales'
			UNION ALL SELECT 'Herramientas Manuales', 'Alicates y pinzas/Tenazas'
			UNION ALL SELECT 'Herramientas Manuales', 'Atornillado/Destornilladores aislados'
			UNION ALL SELECT 'Herramientas Manuales', 'Atornillado/Destornilladores de precisión'
			UNION ALL SELECT 'Herramientas Manuales', 'Atornillado/Destornilladores especiales'
			UNION ALL SELECT 'Herramientas Manuales', 'Atornillado/Destornilladores Phillips'
			UNION ALL SELECT 'Herramientas Manuales', 'Atornillado/Destornilladores planos'
			UNION ALL SELECT 'Herramientas Manuales', 'Atornillado/Destornilladores Torx'
			UNION ALL SELECT 'Herramientas Manuales', 'Atornillado/Llaves de tuerca (nut drivers)'
			UNION ALL SELECT 'Herramientas Manuales', 'Atornillado/Llaves hexagonales (Allen)'
			UNION ALL SELECT 'Herramientas Manuales', 'Atornillado/Llaves Torx manuales'
			UNION ALL SELECT 'Herramientas Manuales', 'Atornillado/Puntas y portapuntas'
			UNION ALL SELECT 'Herramientas Manuales', 'Carpintería/Cepillos de carpintero'
			UNION ALL SELECT 'Herramientas Manuales', 'Carpintería/Herramientas de tallado'
			UNION ALL SELECT 'Herramientas Manuales', 'Carpintería/Limas y escofinas'
			UNION ALL SELECT 'Herramientas Manuales', 'Carpintería/Otras herramientas de carpintero'
			UNION ALL SELECT 'Herramientas Manuales', 'Destornilladores'
			UNION ALL SELECT 'Herramientas Manuales', 'Drywall manual – Acabado y masillado'
			UNION ALL SELECT 'Herramientas Manuales', 'Drywall manual – Accesorios y especiales'
			UNION ALL SELECT 'Herramientas Manuales', 'Drywall manual – Corte y preparación'
			UNION ALL SELECT 'Herramientas Manuales', 'Drywall manual – Instalación y manipulación'
			UNION ALL SELECT 'Herramientas Manuales', 'Electricista manual/Comprobación básica'
			UNION ALL SELECT 'Herramientas Manuales', 'Electricista manual/Corte and pelado'
			UNION ALL SELECT 'Herramientas Manuales', 'Electricista manual/Corte y pelado'
			UNION ALL SELECT 'Herramientas Manuales', 'Electricista manual/Crimpado y engaste'
			UNION ALL SELECT 'Herramientas Manuales', 'Electricista manual/Herramientas de tendido'
			UNION ALL SELECT 'Herramientas Manuales', 'Extractores manuales/Extractores de poleas y engranajes'
			UNION ALL SELECT 'Herramientas Manuales', 'Extractores manuales/Extractores de rodamientos'
			UNION ALL SELECT 'Herramientas Manuales', 'Extractores manuales/Extractores de tornillos y espárragos'
			UNION ALL SELECT 'Herramientas Manuales', 'Extractores manuales/Extractores especiales'
			UNION ALL SELECT 'Herramientas Manuales', 'Extractores manuales/Separadores y apoyos'
			UNION ALL SELECT 'Herramientas Manuales', 'Fontanería manual/Corte de tuberías'
			UNION ALL SELECT 'Herramientas Manuales', 'Fontanería manual/Desatascadores'
			UNION ALL SELECT 'Herramientas Manuales', 'Fontanería manual/Llaves de fontanero'
			UNION ALL SELECT 'Herramientas Manuales', 'Fontanería manual/Roscado y reparación'
			UNION ALL SELECT 'Herramientas Manuales', 'Herramientas automotrices manuales/Encendido y bujías'
			UNION ALL SELECT 'Herramientas Manuales', 'Herramientas automotrices manuales/Frenos'
			UNION ALL SELECT 'Herramientas Manuales', 'Herramientas automotrices manuales/Llaves para filtros'
			UNION ALL SELECT 'Herramientas Manuales', 'Herramientas automotrices manuales/Mecánica general'
			UNION ALL SELECT 'Herramientas Manuales', 'Herramientas automotrices manuales/Neumáticos y ruedas'
			UNION ALL SELECT 'Herramientas Manuales', 'Herramientas de cerrajero manual/Extracción y apertura'
			UNION ALL SELECT 'Herramientas Manuales', 'Herramientas de cerrajero manual/Herramientas de tensión'
			UNION ALL SELECT 'Herramientas Manuales', 'Herramientas de cerrajero manual/Herramientas especiales'
			UNION ALL SELECT 'Herramientas Manuales', 'Herramientas de cerrajero manual/Juegos de ganzúas'
			UNION ALL SELECT 'Herramientas Manuales', 'Herramientas de corte/Cinceles y punzones'
			UNION ALL SELECT 'Herramientas Manuales', 'Herramientas de corte/Cúters y navajas'
			UNION ALL SELECT 'Herramientas Manuales', 'Herramientas de corte/Formones'
			UNION ALL SELECT 'Herramientas Manuales', 'Herramientas de corte/Otros cortantes'
			UNION ALL SELECT 'Herramientas Manuales', 'Herramientas de corte/Tijeras'
			UNION ALL SELECT 'Herramientas Manuales', 'Herramientas HVAC manuales/Abocardado y ensanchado'
			UNION ALL SELECT 'Herramientas Manuales', 'Herramientas HVAC manuales/Doblado y corte de tubería'
			UNION ALL SELECT 'Herramientas Manuales', 'Herramientas HVAC manuales/Instalación y servicio'
			UNION ALL SELECT 'Herramientas Manuales', 'Herramientas manuales especializadas/Chapas y lámina'
			UNION ALL SELECT 'Herramientas Manuales', 'Herramientas manuales especializadas/Cortadores especiales'
			UNION ALL SELECT 'Herramientas Manuales', 'Herramientas manuales especializadas/Herramientas de alineación'
			UNION ALL SELECT 'Herramientas Manuales', 'Herramientas manuales especializadas/Prensas y mordazas'
			UNION ALL SELECT 'Herramientas Manuales', 'Jardinería manual/Herramientas de corte jardín'
			UNION ALL SELECT 'Herramientas Manuales', 'Jardinería manual/Herramientas de labranza'
			UNION ALL SELECT 'Herramientas Manuales', 'Jardinería manual/Herramientas de plantación'
			UNION ALL SELECT 'Herramientas Manuales', 'Jardinería manual/Herramientas forestales'
			UNION ALL SELECT 'Herramientas Manuales', 'Juegos de herramientas manuales/Juegos generales'
			UNION ALL SELECT 'Herramientas Manuales', 'Juegos de herramientas manuales/Juegos para carpintero'
			UNION ALL SELECT 'Herramientas Manuales', 'Juegos de herramientas manuales/Juegos para mecánico'
			UNION ALL SELECT 'Herramientas Manuales', 'Juegos de herramientas manuales/Juegos para plomero'
			UNION ALL SELECT 'Herramientas Manuales', 'Limas y escofinas'
			UNION ALL SELECT 'Herramientas Manuales', 'Llaves manuales'
			UNION ALL SELECT 'Herramientas Manuales', 'Llaves manuales/Accesorios para vasos'
			UNION ALL SELECT 'Herramientas Manuales', 'Llaves manuales/Llaves ajustables'
			UNION ALL SELECT 'Herramientas Manuales', 'Llaves manuales/Llaves combinadas en pulgadas'
			UNION ALL SELECT 'Herramientas Manuales', 'Llaves manuales/Llaves combinadas métricas'
			UNION ALL SELECT 'Herramientas Manuales', 'Llaves manuales/Llaves de estrella en pulgadas'
			UNION ALL SELECT 'Herramientas Manuales', 'Llaves manuales/Llaves de estrella métricas'
			UNION ALL SELECT 'Herramientas Manuales', 'Llaves manuales/Llaves de tubo'
			UNION ALL SELECT 'Herramientas Manuales', 'Llaves manuales/Llaves de vaso y carracas'
			UNION ALL SELECT 'Herramientas Manuales', 'Llaves manuales/Llaves especiales'
			UNION ALL SELECT 'Herramientas Manuales', 'Llaves manuales/Llaves fijas en pulgadas'
			UNION ALL SELECT 'Herramientas Manuales', 'Llaves manuales/Llaves fijas métricas'
			UNION ALL SELECT 'Herramientas Manuales', 'Llaves manuales/Vasos de impacto en pulgadas'
			UNION ALL SELECT 'Herramientas Manuales', 'Llaves manuales/Vasos de impacto métricos'
			UNION ALL SELECT 'Herramientas Manuales', 'Llaves manuales/Vasos en pulgadas'
			UNION ALL SELECT 'Herramientas Manuales', 'Llaves manuales/Vasos métricos'
			UNION ALL SELECT 'Herramientas Manuales', 'Martillos and percusión/Punzones y botadores'
			UNION ALL SELECT 'Herramientas Manuales', 'Martillos y mazas'
			UNION ALL SELECT 'Herramientas Manuales', 'Martillos y percusión/Macetas y cinceles'
			UNION ALL SELECT 'Herramientas Manuales', 'Martillos y percusión/Martillos de bola'
			UNION ALL SELECT 'Herramientas Manuales', 'Martillos y percusión/Martillos de demolición'
			UNION ALL SELECT 'Herramientas Manuales', 'Martillos y percusión/Martillos de uña'
			UNION ALL SELECT 'Herramientas Manuales', 'Martillos y percusión/Martillos especializados'
			UNION ALL SELECT 'Herramientas Manuales', 'Martillos y percusión/Mazas'
			UNION ALL SELECT 'Herramientas Manuales', 'Martillos y percusión/Palancas y demolición'
			UNION ALL SELECT 'Herramientas Manuales', 'Martillos y percusión/Punzones y botadores'
			UNION ALL SELECT 'Herramientas Manuales', 'Medición/Cintas métricas y reglas'
			UNION ALL SELECT 'Herramientas Manuales', 'Medición/Escuadras y ángulos'
			UNION ALL SELECT 'Herramientas Manuales', 'Medición/Herramientas de marcación'
			UNION ALL SELECT 'Herramientas Manuales', 'Medición/Instrumentos de medición'
			UNION ALL SELECT 'Herramientas Manuales', 'Otros manuales/Otros manuales'
			UNION ALL SELECT 'Herramientas Manuales', 'Perforación manual/Brocas para concreto'
			UNION ALL SELECT 'Herramientas Manuales', 'Perforación manual/Brocas para madera'
			UNION ALL SELECT 'Herramientas Manuales', 'Perforación manual/Brocas para metal HSS'
			UNION ALL SELECT 'Herramientas Manuales', 'Perforación manual/Sierras perforadoras'
			UNION ALL SELECT 'Herramientas Manuales', 'Perforación manual/Taladros manuales'
			UNION ALL SELECT 'Herramientas Manuales', 'Pintura y acabados/Aplicadores de sellador'
			UNION ALL SELECT 'Herramientas Manuales', 'Pintura y acabados/Brochas y rodillos'
			UNION ALL SELECT 'Herramientas Manuales', 'Pintura y acabados/Espátulas y rascadores'
			UNION ALL SELECT 'Herramientas Manuales', 'Pintura y acabados/Lijado manual'
			UNION ALL SELECT 'Herramientas Manuales', 'Pintura y acabados/Otros'
			UNION ALL SELECT 'Herramientas Manuales', 'Prensas y sargentos'
			UNION ALL SELECT 'Herramientas Manuales', 'Remachado y fijación manual/Grapadoras manuales'
			UNION ALL SELECT 'Herramientas Manuales', 'Remachado y fijación manual/Pinzas y útiles de fijación'
			UNION ALL SELECT 'Herramientas Manuales', 'Remachado y fijación manual/Remachadoras'
			UNION ALL SELECT 'Herramientas Manuales', 'Repuestos y accesorios/Hojas y cuchillas'
			UNION ALL SELECT 'Herramientas Manuales', 'Repuestos y accesorios/Mangos de herramientas'
			UNION ALL SELECT 'Herramientas Manuales', 'Roscado manual/Avellanadores'
			UNION ALL SELECT 'Herramientas Manuales', 'Roscado manual/Calibradores y peines de rosca'
			UNION ALL SELECT 'Herramientas Manuales', 'Roscado manual/Escariadores'
			UNION ALL SELECT 'Herramientas Manuales', 'Roscado manual/Juegos de roscado'
			UNION ALL SELECT 'Herramientas Manuales', 'Roscado manual/Machos de roscar'
			UNION ALL SELECT 'Herramientas Manuales', 'Roscado manual/Porta terrajas y manerales'
			UNION ALL SELECT 'Herramientas Manuales', 'Roscado manual/Terrajas'
			UNION ALL SELECT 'Herramientas Manuales', 'Sierras manuales'
			UNION ALL SELECT 'Herramientas Manuales', 'Sierras y serruchos/Hojas de sierra'
			UNION ALL SELECT 'Herramientas Manuales', 'Sierras y serruchos/Sierras especiales'
			UNION ALL SELECT 'Herramientas Manuales', 'Sierras y serruchos/Sierras para madera'
			UNION ALL SELECT 'Herramientas Manuales', 'Sierras y serruchos/Sierras para metal'
			UNION ALL SELECT 'Herramientas Manuales', 'Sujeción/Otras sujeciones'
			UNION ALL SELECT 'Herramientas Manuales', 'Sujeción/Sargentos y prensas'
			UNION ALL SELECT 'Herramientas Manuales', 'Sujeción/Tornillos de banco'
			UNION ALL SELECT 'Herramientas Neumáticas', 'Atornillado neumático/Atornilladores neumáticos'
			UNION ALL SELECT 'Herramientas Neumáticas', 'Automotriz neumático/Herramientas automotrices'
			UNION ALL SELECT 'Herramientas Neumáticas', 'Compresores/Accesorios de compresores'
			UNION ALL SELECT 'Herramientas Neumáticas', 'Compresores/Compresores estacionarios'
			UNION ALL SELECT 'Herramientas Neumáticas', 'Compresores/Compresores portátiles'
			UNION ALL SELECT 'Herramientas Neumáticas', 'Corte especializado neumático/Corte metálico'
			UNION ALL SELECT 'Herramientas Neumáticas', 'Corte especializado neumático/Otros cortes'
			UNION ALL SELECT 'Herramientas Neumáticas', 'Corte neumático/Sierras neumáticas'
			UNION ALL SELECT 'Herramientas Neumáticas', 'Herramientas de fijación neumáticas'
			UNION ALL SELECT 'Herramientas Neumáticas', 'Herramientas de impacto neumáticas'
			UNION ALL SELECT 'Herramientas Neumáticas', 'Herramientas rotativas neumáticas/Herramientas rotativas'
			UNION ALL SELECT 'Herramientas Neumáticas', 'HVAC neumático/Herramientas HVAC'
			UNION ALL SELECT 'Herramientas Neumáticas', 'Juegos neumáticos/Juegos de herramientas'
			UNION ALL SELECT 'Herramientas Neumáticas', 'Llaves de impacto/Llaves de impacto neumáticas'
			UNION ALL SELECT 'Herramientas Neumáticas', 'Percusión neumática/Martillos neumáticos'
			UNION ALL SELECT 'Herramientas Neumáticas', 'Pistolas neumáticas/Pistolas de engrase'
			UNION ALL SELECT 'Herramientas Neumáticas', 'Pistolas neumáticas/Pistolas de pintura'
			UNION ALL SELECT 'Herramientas Neumáticas', 'Pistolas neumáticas/Pistolas de soplado'
			UNION ALL SELECT 'Herramientas Neumáticas', 'Pulido y lijado neumático'
			UNION ALL SELECT 'Herramientas Neumáticas', 'Taladros neumáticos/Taladros neumáticos'
			UNION ALL SELECT 'Hierro Y Acero', 'Aceros Estructurales'
			UNION ALL SELECT 'Hierro Y Acero', 'Alambres Y Mallas'
			UNION ALL SELECT 'Hierro Y Acero', 'Barras Y Varillas'
			UNION ALL SELECT 'Hierro Y Acero', 'Derivados Del Acero'
			UNION ALL SELECT 'Hierro Y Acero', 'Perfiles'
			UNION ALL SELECT 'Hierro Y Acero', 'Productos De Acero Inoxidable'
			UNION ALL SELECT 'Hierro Y Acero', 'Tuberías Metálicas'
			UNION ALL SELECT 'Hierros y Perfiles', 'Perfiles estructurales'
			UNION ALL SELECT 'Hierros y Perfiles', 'Perfiles livianos'
			UNION ALL SELECT 'Hogar, Camping y Decoración', 'Accesorios para hogar'
			UNION ALL SELECT 'Hogar, Camping y Decoración', 'Artículos de limpieza para hogar'
			UNION ALL SELECT 'Hogar, Camping y Decoración', 'Camping y aire libre'
			UNION ALL SELECT 'Hogar, Camping y Decoración', 'Decoración y ambientación'
			UNION ALL SELECT 'Hogar, Camping y Decoración', 'Equipos para camping'
			UNION ALL SELECT 'Hogar, Camping y Decoración', 'Organización y almacenamiento en hogar'
			UNION ALL SELECT 'Hogar, Camping y Decoración', 'Parrillas y asadores'
			UNION ALL SELECT 'HVAC (Refrigeración y Aire Acondicionado)', 'Accesorios de climatización'
			UNION ALL SELECT 'HVAC (Refrigeración y Aire Acondicionado)', 'Bandejas y soportes'
			UNION ALL SELECT 'HVAC (Refrigeración y Aire Acondicionado)', 'Controles y termostatos'
			UNION ALL SELECT 'HVAC (Refrigeración y Aire Acondicionado)', 'Difusores y rejillas'
			UNION ALL SELECT 'HVAC (Refrigeración y Aire Acondicionado)', 'Drenaje de condensados'
			UNION ALL SELECT 'HVAC (Refrigeración y Aire Acondicionado)', 'Ductos y accesorios'
			UNION ALL SELECT 'HVAC (Refrigeración y Aire Acondicionado)', 'Equipos de aire acondicionado'
			UNION ALL SELECT 'HVAC (Refrigeración y Aire Acondicionado)', 'Equipos de climatización'
			UNION ALL SELECT 'HVAC (Refrigeración y Aire Acondicionado)', 'Filtros de aire'
			UNION ALL SELECT 'HVAC (Refrigeración y Aire Acondicionado)', 'Herramientas específicas HVAC'
			UNION ALL SELECT 'HVAC (Refrigeración y Aire Acondicionado)', 'Refrigerantes'
			UNION ALL SELECT 'HVAC (Refrigeración y Aire Acondicionado)', 'Tubería y aislamiento frigorífico'
			UNION ALL SELECT 'HVAC (Refrigeración y Aire Acondicionado)', 'Válvulas y componentes frigoríficos'
			UNION ALL SELECT 'HVAC (Refrigeración y Aire Acondicionado)', 'Ventilación y extracción'
			UNION ALL SELECT 'Iluminación', 'Accesorios'
			UNION ALL SELECT 'Iluminación', 'Fluorescentes'
			UNION ALL SELECT 'Iluminación', 'Iluminación De Emergencia'
			UNION ALL SELECT 'Iluminación', 'Iluminación Decorativa'
			UNION ALL SELECT 'Iluminación', 'Iluminación Exterior'
			UNION ALL SELECT 'Iluminación', 'Iluminación industrial'
			UNION ALL SELECT 'Iluminación', 'Iluminación Interior'
			UNION ALL SELECT 'Iluminación', 'Iluminación Técnica'
			UNION ALL SELECT 'Iluminación', 'Incandescentes'
			UNION ALL SELECT 'Iluminación', 'Lámparas Especiales'
			UNION ALL SELECT 'Iluminación', 'LED'
			UNION ALL SELECT 'Iluminación', 'Luminarias de exterior'
			UNION ALL SELECT 'Iluminación', 'Luminarias de interior'
			UNION ALL SELECT 'Iluminación', 'Reflectores'
			UNION ALL SELECT 'Impermeabilización', 'Accesorios de aplicación para impermeabilización'
			UNION ALL SELECT 'Impermeabilización', 'Cintas, bandas y accesorios impermeables'
			UNION ALL SELECT 'Impermeabilización', 'Impermeabilización de baños y áreas húmedas'
			UNION ALL SELECT 'Impermeabilización', 'Impermeabilización de cimentaciones y sótanos'
			UNION ALL SELECT 'Impermeabilización', 'Impermeabilizantes cementicios y morteros'
			UNION ALL SELECT 'Impermeabilización', 'Impermeabilizantes líquidos'
			UNION ALL SELECT 'Impermeabilización', 'Impermeabilizantes para muros y fachadas'
			UNION ALL SELECT 'Impermeabilización', 'Impermeabilizantes para techos y terrazas'
			UNION ALL SELECT 'Impermeabilización', 'Láminas impermeables'
			UNION ALL SELECT 'Impermeabilización', 'Membranas y mantos asfálticos'
			UNION ALL SELECT 'Impermeabilización', 'Selladores específicos para impermeabilización'
			UNION ALL SELECT 'Impermeabilización', 'Sistemas de drenaje y alivio de presión'
			UNION ALL SELECT 'Jardín y Agrícola', 'Accesorios de cultivo y soporte'
			UNION ALL SELECT 'Jardín y Agrícola', 'Almacenamiento y organización de jardín'
			UNION ALL SELECT 'Jardín y Agrícola', 'Carretillas y transporte de jardín'
			UNION ALL SELECT 'Jardín y Agrícola', 'Cercas y delimitación de jardín'
			UNION ALL SELECT 'Jardín y Agrícola', 'Equipos de riego'
			UNION ALL SELECT 'Jardín y Agrícola', 'Equipos motorizados de jardín'
			UNION ALL SELECT 'Jardín y Agrícola', 'Herramientas de jardín'
			UNION ALL SELECT 'Jardín y Agrícola', 'Pulverización y fumigación'
			UNION ALL SELECT 'Jardín y Agrícola', 'Riego de jardín y agrícola'
			UNION ALL SELECT 'Limpieza y Aseo', 'Accesorios de aseo'
			UNION ALL SELECT 'Limpieza y Aseo', 'Accesorios de aseo institucional'
			UNION ALL SELECT 'Limpieza y Aseo', 'Basureros y contenedores'
			UNION ALL SELECT 'Limpieza y Aseo', 'Bolsas de basura'
			UNION ALL SELECT 'Limpieza y Aseo', 'Implementos de limpieza manual'
			UNION ALL SELECT 'Limpieza y Aseo', 'Limpieza de pisos'
			UNION ALL SELECT 'Limpieza y Aseo', 'Limpieza de vidrios'
			UNION ALL SELECT 'Limpieza y Aseo', 'Paños, microfibras y esponjas'
			UNION ALL SELECT 'Limpieza y Aseo', 'Utensilios de limpieza'
			UNION ALL SELECT 'Lubricantes y Grasas', 'Aceites de transmisión y engranajes'
			UNION ALL SELECT 'Lubricantes y Grasas', 'Aceites hidráulicos y para compresor'
			UNION ALL SELECT 'Lubricantes y Grasas', 'Aceites para motor'
			UNION ALL SELECT 'Lubricantes y Grasas', 'Grasas lubricantes'
			UNION ALL SELECT 'Lubricantes y Grasas', 'Lubricantes'
			UNION ALL SELECT 'Lubricantes y Grasas', 'Lubricantes especiales en spray'
			UNION ALL SELECT 'Lubricantes y Grasas', 'Lubricantes especiales varios'
			UNION ALL SELECT 'Madera Y Derivados', 'Accesorios Y Componentes'
			UNION ALL SELECT 'Madera Y Derivados', 'Elementos Estructurales'
			UNION ALL SELECT 'Madera Y Derivados', 'Maderas Naturales'
			UNION ALL SELECT 'Madera Y Derivados', 'Molduras Y Acabados'
			UNION ALL SELECT 'Madera y Derivados', 'Molduras y listones'
			UNION ALL SELECT 'Madera Y Derivados', 'Pisos De Madera'
			UNION ALL SELECT 'Madera Y Derivados', 'Puertas Y Ventanas'
			UNION ALL SELECT 'Madera Y Derivados', 'Revestimientos'
			UNION ALL SELECT 'Madera y Derivados', 'Tableros de madera'
			UNION ALL SELECT 'Madera Y Derivados', 'Tableros Y Láminas'
			UNION ALL SELECT 'Materiales de Construcción', 'Adoquines y piezas para pavimento'
			UNION ALL SELECT 'Materiales de Construcción', 'Áridos y agregados'
			UNION ALL SELECT 'Materiales de Construcción', 'Cementos, cales y yesos'
			UNION ALL SELECT 'Materiales de Construcción', 'Ladrillos y bloques'
			UNION ALL SELECT 'Materiales de Construcción', 'Materiales básicos'
			UNION ALL SELECT 'Materiales de Construcción', 'Morteros y mezclas preparadas'
			UNION ALL SELECT 'Materiales de Construcción', 'Paneles y placas'
			UNION ALL SELECT 'Materiales de Construcción', 'Placas y paneles de construcción'
			UNION ALL SELECT 'Materiales de Construcción', 'Productos para juntas y nivelación'
			UNION ALL SELECT 'Materiales de Construcción', 'Revestimientos Y Pisos'
			UNION ALL SELECT 'Materiales de Construcción', 'Techos Y Cubiertas'
			UNION ALL SELECT 'Pintura Y Acabados', 'Abrasivos Y Preparación'
			UNION ALL SELECT 'Pintura Y Acabados', 'Accesorios De Aplicación'
			UNION ALL SELECT 'Pintura Y Acabados', 'Aditivos Y Complementos'
			UNION ALL SELECT 'Pintura Y Acabados', 'Almacenamiento Y Transporte'
			UNION ALL SELECT 'Pintura Y Acabados', 'Cintas Y Enmascarado'
			UNION ALL SELECT 'Pintura Y Acabados', 'Color Y Mezclado'
			UNION ALL SELECT 'Pintura Y Acabados', 'Colorantes y tintas'
			UNION ALL SELECT 'Pintura Y Acabados', 'Ensayos Y Control De Calidad'
			UNION ALL SELECT 'Pintura Y Acabados', 'Equipos De Pintura'
			UNION ALL SELECT 'Pintura Y Acabados', 'Imprimaciones Y Primers'
			UNION ALL SELECT 'Pintura Y Acabados', 'Mantenimiento Y Limpieza'
			UNION ALL SELECT 'Pintura Y Acabados', 'Masillas Y Rellenos'
			UNION ALL SELECT 'Pintura Y Acabados', 'Pinturas'
			UNION ALL SELECT 'Pintura Y Acabados', 'Productos Especiales'
			UNION ALL SELECT 'Pintura Y Acabados', 'Revestimientos Especiales'
			UNION ALL SELECT 'Pinturas y Complementos', 'Complementos de pintura'
			UNION ALL SELECT 'Pinturas y Complementos', 'Pinturas arquitectónicas'
			UNION ALL SELECT 'Plomería', 'Accesorios De Tubería'
			UNION ALL SELECT 'Plomería', 'Bombas'
			UNION ALL SELECT 'Plomería', 'Conectores Y Mangueras'
			UNION ALL SELECT 'Plomería', 'Conexiones De Hierro Negro'
			UNION ALL SELECT 'Plomería', 'Conexiones Galvanizadas'
			UNION ALL SELECT 'Plomería', 'Conexiones PEX'
			UNION ALL SELECT 'Plomería', 'Conexiones PPR'
			UNION ALL SELECT 'Plomería', 'Conexiones PVC'
			UNION ALL SELECT 'Plomería', 'Conexiones PVC-O'
			UNION ALL SELECT 'Plomería', 'Desagües y sifones'
			UNION ALL SELECT 'Plomería', 'Filtros Y Purificación'
			UNION ALL SELECT 'Plomería', 'Herramientas y Equipos'
			UNION ALL SELECT 'Plomería', 'Llaves de paso'
			UNION ALL SELECT 'Plomería', 'Llaves y válvulas'
			UNION ALL SELECT 'Plomería', 'Repuestos y Accesorios'
			UNION ALL SELECT 'Plomería', 'Selladores Y Empaques'
			UNION ALL SELECT 'Plomería', 'Sifones Y Drenaje'
			UNION ALL SELECT 'Plomería', 'Termofusión - Accesorios'
			UNION ALL SELECT 'Plomería', 'Termofusión - Control Y Registro'
			UNION ALL SELECT 'Plomería', 'Termofusión - Transiciones'
			UNION ALL SELECT 'Plomería', 'Tuberías'
			UNION ALL SELECT 'Plomería', 'Válvulas'
			UNION ALL SELECT 'Productos Químicos y Limpieza', 'Control de plagas químico'
			UNION ALL SELECT 'Productos Químicos y Limpieza', 'Desengrasantes y desincrustantes'
			UNION ALL SELECT 'Productos Químicos y Limpieza', 'Desinfectantes y sanitizantes'
			UNION ALL SELECT 'Productos Químicos y Limpieza', 'Limpieza de manos industrial'
			UNION ALL SELECT 'Productos Químicos y Limpieza', 'Limpieza profesional e industrial'
			UNION ALL SELECT 'Productos Químicos y Limpieza', 'Productos químicos automotrices de limpieza'
			UNION ALL SELECT 'Productos Químicos y Limpieza', 'Productos químicos de construcción'
			UNION ALL SELECT 'Productos Químicos y Limpieza', 'Productos químicos para construcción'
			UNION ALL SELECT 'Productos Químicos y Limpieza', 'Productos químicos para piscinas y agua'
			UNION ALL SELECT 'Productos Químicos y Limpieza', 'Químicos de mantenimiento'
			UNION ALL SELECT 'Productos Químicos y Limpieza', 'Solventes y diluyentes'
			UNION ALL SELECT 'Productos Químicos y Limpieza', 'Tratamiento y protección de superficies'
			UNION ALL SELECT 'Seguridad Industrial (EPP)', 'Accesorios de seguridad personal'
			UNION ALL SELECT 'Seguridad Industrial (EPP)', 'Protección auditiva'
			UNION ALL SELECT 'Seguridad Industrial (EPP)', 'Protección contra caídas'
			UNION ALL SELECT 'Seguridad Industrial (EPP)', 'Protección corporal'
			UNION ALL SELECT 'Seguridad Industrial (EPP)', 'Protección craneal'
			UNION ALL SELECT 'Seguridad Industrial (EPP)', 'Protección de cuerpo'
			UNION ALL SELECT 'Seguridad Industrial (EPP)', 'Protección ocular y facial'
			UNION ALL SELECT 'Seguridad Industrial (EPP)', 'Protección para manos'
			UNION ALL SELECT 'Seguridad Industrial (EPP)', 'Protección para pies'
			UNION ALL SELECT 'Seguridad Industrial (EPP)', 'Protección respiratoria'
			UNION ALL SELECT 'Seguridad y Señalización', 'Cintas y barreras de seguridad'
			UNION ALL SELECT 'Seguridad y Señalización', 'Elementos de seguridad física'
			UNION ALL SELECT 'Seguridad y Señalización', 'Espejos y balizamiento'
			UNION ALL SELECT 'Seguridad y Señalización', 'Postes, bases y soportes para señalización'
			UNION ALL SELECT 'Seguridad y Señalización', 'Señales adhesivas y etiquetas de seguridad'
			UNION ALL SELECT 'Seguridad y Señalización', 'Señalización fotoluminiscente'
			UNION ALL SELECT 'Seguridad y Señalización', 'Señalización industrial y de seguridad'
			UNION ALL SELECT 'Seguridad y Señalización', 'Señalización vial'
			UNION ALL SELECT 'Seguridad y Señalización', 'Señalización vial y de obra'
			UNION ALL SELECT 'Soldadura', 'Accesorios de soldadura'
			UNION ALL SELECT 'Soldadura', 'Accesorios Para Soplete'
			UNION ALL SELECT 'Soldadura', 'Consumibles'
			UNION ALL SELECT 'Soldadura', 'Consumibles de soldadura'
			UNION ALL SELECT 'Soldadura', 'Equipos De Corte'
			UNION ALL SELECT 'Soldadura', 'Equipos De Soldadura'
			UNION ALL SELECT 'Soldadura', 'Gases'
			UNION ALL SELECT 'Soldadura', 'Herramientas Y Equipos Auxiliares'
			UNION ALL SELECT 'Soldadura', 'Limpieza Y Mantenimiento'
			UNION ALL SELECT 'Soldadura', 'Picos Y Boquillas'
			UNION ALL SELECT 'Soldadura', 'Preparación y limpieza de soldadura'
			UNION ALL SELECT 'Soldadura', 'Repuestos'
			UNION ALL SELECT 'Techos y Cobertizos', 'Accesorios de techo'
			UNION ALL SELECT 'Techos y Cobertizos', 'Cubiertas'
			UNION ALL SELECT 'Tornillería y Fijaciones', 'Abrazaderas y fijaciones metálicas'
			UNION ALL SELECT 'Tornillería y Fijaciones', 'Anclajes mecánicos'
			UNION ALL SELECT 'Tornillería y Fijaciones', 'Anclajes mecánicos y químicos'
			UNION ALL SELECT 'Tornillería y Fijaciones', 'Anclajes químicos'
			UNION ALL SELECT 'Tornillería y Fijaciones', 'Arandelas'
			UNION ALL SELECT 'Tornillería y Fijaciones', 'Clavos y puntas'
			UNION ALL SELECT 'Tornillería y Fijaciones', 'Fijaciones para techos y láminas'
			UNION ALL SELECT 'Tornillería y Fijaciones', 'Fijaciones plásticas'
			UNION ALL SELECT 'Tornillería y Fijaciones', 'Grapas y fijaciones'
			UNION ALL SELECT 'Tornillería y Fijaciones', 'Remaches'
			UNION ALL SELECT 'Tornillería y Fijaciones', 'Tarugos y tacos plásticos'
			UNION ALL SELECT 'Tornillería y Fijaciones', 'Tornillos autoperforantes'
			UNION ALL SELECT 'Tornillería y Fijaciones', 'Tornillos drywall'
			UNION ALL SELECT 'Tornillería y Fijaciones', 'Tornillos especiales'
			UNION ALL SELECT 'Tornillería y Fijaciones', 'Tornillos para madera'
			UNION ALL SELECT 'Tornillería y Fijaciones', 'Tornillos para metal'
			UNION ALL SELECT 'Tornillería y Fijaciones', 'Tuercas'
			UNION ALL SELECT 'Tuberías y Conexiones', 'Conexiones para tubería'
			UNION ALL SELECT 'Tuberías y Conexiones', 'Tuberías para agua'
			UNION ALL SELECT 'Varios', 'Accesorios generales'
			UNION ALL SELECT 'Varios', 'Organización y orden'
		) AS raw_pairs
		GROUP BY
			LOWER(TRIM(raw_pairs.raw_category)),
			LOWER(TRIM(raw_pairs.raw_subcategory))
	) AS src
	INNER JOIN Category c
		ON LOWER(TRIM(c.name)) = src.normalized_category
	LEFT JOIN Subcategory s
		ON s.id_category_fk = c.id_category
	   AND LOWER(TRIM(s.name)) = src.normalized_subcategory
	WHERE s.id_subcategory IS NULL;

END //

DELIMITER ;

-- Ejecutar con:
CALL sp_seed_master_subcategories();
